### ISSUE TITLE
When a document is already in a corpus...

### ISSUE THREAD

**Issue by benel** [Hypertopic/LaSuli#14]
... use this corpus instead of the user's "bookmarks".

This applies especially to texts in Cassandre, since all of them are already recorded as being in a corpus

**Comment by Slaals** [comment]
I'm currently working on it, I need some insights to continue!

First I found a way to get the existing item id as id when LaSuli posts the item in the default server (argos as it is in your example).

But for the corpus it's a bit though. Actually, when LaSuli creates a corpus item it calls the method `createWithId(id, name)`. The point is, when this method is called, the same variable is put as parameters : as id and as name. I'm only able to get the corpus name of the resource.

Now, I need some insights. In Steatite, an item and a corpus have both the same id. Regarding to this, it could be a solution to get the corpus name and to get the item id in order to call the method `createWithId(itemId, corpusName)`. This would be correct for the Steatite case, but what about other servers?

**Comment by benel** [comment]
> First I found a way to get the existing item id as id when LaSuli posts the item in the default server (argos as it is in your example).

I created a patch for this yesterday. I will push it on a dev branch (since there are other related issues to be fixed).

> In Steatite, an item and a corpus have both the same id. 

What do you mean? 
For example `71ff73e95a7df128d247c01d0892ba5c3c7cbfe0` is an item ID while `Vitraux - Bénel` is its corpus ID.

**Comment by Slaals** [comment]
> For example 71ff73e95a7df128d247c01d0892ba5c3c7cbfe0 is an item ID while Vitraux - Bénel is its corpus ID.

That exactly what I meant. I thought at first a corpus id was the item id. The database structure in Steatite looks like that `(id, attribute, value)`.

So, for an item `71ff73e95a7df128d247c01d0892ba5c3c7cbfe0`, in Steatite we have : 
`(71ff73e95a7df128d247c01d0892ba5c3c7cbfe0, name, SNZ 004)`
`(71ff73e95a7df128d247c01d0892ba5c3c7cbfe0, corpus, Vitraux - Bénel)`

Here the corpus ID and the item ID are the same. I mistaken corpus ID because of that, but now it's clearer.

Your solution has the same result as mine and it's shorter :+1: .

> (since there are other related issues to be fixed).

Are you refering to issues in this ticket? Does your solution resolve all the issues?

**Comment by benel** [comment]
> Here the corpus ID and the item ID are the same. I mistaken corpus ID because of that, but now it's clearer.

`(71ff73e95a7df128d247c01d0892ba5c3c7cbfe0, corpus, Vitraux - Bénel)`
should be read as "item `71ff...`'s `corpus` is `Vitraux - Bénel`".

This is a triple notation just like in RDF.

**Comment by benel** [comment]
>> (since there are other related issues to be fixed).

> Are you refering to issues in this ticket? Does your solution resolve all the issues?

There is a related problem with the `name` attribute: only the name from the read-write server is shown. This prevents to test easily (from the user interface) that the patch worked.

Highlights are also broken, but this seems to be unrelated with my patch.

**Comment by Slaals** [comment]
> There is a related problem with the name attribute: only the name from the read-write server is shown.
This puts the light on more than only a UI issue, the backend. My point is, actually LaSuli only uses the name from the default server (read-write server).

With that said, we have to tell LaSuli which name to show AND which name it should write in, regarding this we would have to change some backend codes in my opinion. Because when you rename an item, it creates, or renames, directly on the default server.

I hope I was clear enough. For the moment I made something that shows the original name of the item if it doesn't exist in the default server.
