### ISSUE TITLE
Add the current site to the white list of analyzable Web sites

### ISSUE THREAD

**Issue by benel** [Hypertopic/LaSuli#26]
Despite our warnings, some users continue to keep LaSuli opened while browsing sites they don't want to analyze.

This is a double concern:
- for users' privacy (Hypertopic services administrators can see users' browsing history),
- for services stress (100 users doing requests every 5 seconds all day long).

This could be fixed with a white list of analyzable Web sites in LaSuli settings:
the first time a user would like to see analyses on a site, he would allow LaSuli to do so.

**Comment by florentpergoud** [comment]
We discussed about using the same interface as the extension « Add block » to handle which website has to be analyzed or not.

We can :

- Create a tab in the Option page with the white list
![](https://mdn.mozillademos.org/files/14039/popup-shadow.png)

- Put an item « add to whitelist » in the context menu
![](https://mdn.mozillademos.org/files/15051/context_menu_example.png)

- Put in the popup window of the address bar button an option to add the current URL to the whitelist 
![](https://mdn.mozillademos.org/files/15055/options_page.png)

**Comment by benel** [comment]
A click to the toolbar button (to show annotations) is probably the most ergonomic solution for users to add a site to the white list. But it should also be modified (set or unset) in the option page of the extension.

**Comment by gnoxr** [comment]
I believe whitelist management is a major feature (ie, required before releasing the v3), since I find the current behavior problematic (the extension button checks every page we visit for annotations, unless we uninstall the extension).

I'm not working on it rn, but here is a sample draft for a popup (when the user clicks the toolbar button).
![a popup allowing to whitelist the current web page, open the sidebar, or show advanced options](https://user-images.githubusercontent.com/7422439/37912730-a7b63d6a-3102-11e8-84b7-71ea3cfa9a83.png)
